### ISSUE TITLE
Atomicity Support

### ISSUE THREAD

**Issue by sinlerdev** [vinum-team/Vinum#25]
Atomic transactions' support is highly useful, and can provide an efficient method for Vinum users to update objects without accidentally triggering more than one update on a tree when not needed.

Perhaps this is the only issue I thought about its details for a lot of time, but I am not giving a lot of information about it for now because it can become irrelevant by the time I work on it.

**Comment by sinlernick** [comment]
Atomic updates in the form of a `BatchWrite` public operator could be useful in certain cases where two or more dependencies could change at the same time, and most importantly, these dependencies have overlapping dependents but at the same time also have unique dependents. 

How Vinum would implement it is entirely internal and shouldn't be a concern to the public, but since GNR (Generalized Node Reduction) algorithm is implemented into `UpdateAll`, the simplest solution is to create a RNode that houses all of these dependencies as dependents, and then call the function on that RNode.


However, a very important question arises when dealing with `BatchWrite`; how are we gonna typecheck this operator? Technically speaking, Luau lacks the ability to enable typechecking, so the "best" solution could be the introduction of a "Transaction" scope like where one could use `DeferWrite` and these results are then applied after the Transaction has ended, preferably with an internal equivalent to BatchWrite, something like this:
```lua
Transaction(function(DeferWrite)
    DeferWrite(state1, 1)
    DeferWrite(state2, 2)
end) -- after this function is executed, all data is then applied with BatchWrite.
```

**Comment by sinlernick** [comment]
It could be useful to publicize both BatchWrite and Transaction, so that both act as different solutions for different problems.

**Comment by sinlernick** [comment]
Final Design:

Barebones:
```lua
Batch(object, data, object2, data2)
```

Safe:
```lua
Batch(Info(object, data), Info(object2, data2))
```

`Info` in this scenario is simply just `(object: State<T>, data: T) -> (State<T>, data: T)`, as such, its is easily inline-able, and doesn't introduce any memory allocation, and as a bonus, is entirely optional.

**Comment by sinlernick** [comment]
A slight issue with the `safe` option in the final design is that Luau is just.. kind of awkward with multiple return values, which results in values getting dropped. For now, I am pushing the barebones implementation, and will look at possible solutions later.

**Comment by sinlernick** [comment]
Upon further inspection, running into mistakes concerning Batch and typechecking is actually minimal due to the relatively simple API.
